package com.hansson.shithead.rr;

public enum ResponseStatus {
	OK, NOT_OK, EMAL_OR_USERNAME_EXISTS, INVALID_CREDENTIALS, INVALID_GAME, CHANCE_TAKEN, OTHER_PLAYER, BAD_VERSION, FRIEND_EXISTS, FRIEND_NOT_EXISTS
}
