package com.hansson.shithead.util;

import java.util.HashMap;
import java.util.Map;

import com.hansson.shithead.R;

public class Constants {

	// Preference constants
	public static final String PREF_TAG = "shit.head.preferences";
	public static final String PREF_USERNAME = "username";
	public static final String PREF_REGID = "regId";
	public static final String PREF_SESSION = "sessionId";
	public static final String PREF_PASSWORD = "password";
	public static final String PREF_AUTO_LOGIN = "auto_login";
	// Misc
	public static final String URL = HiddenConstants.URL;
	public static final String CONNECTION_ERROR = "Connection error";
	public static final String LOG_TAG = "SHH_TAG";
	public static final int REGISTER_ACTIVITY_CODE = 0x1111;
	// Maps containing card drawables and corresponding string
	public static final Map<String, Integer> CARD_MAP = new HashMap<String, Integer>();
	static {
		CARD_MAP.put("21", R.drawable.hearts_2);
		CARD_MAP.put("31", R.drawable.hearts_3);
		CARD_MAP.put("41", R.drawable.hearts_4);
		CARD_MAP.put("51", R.drawable.hearts_5);
		CARD_MAP.put("61", R.drawable.hearts_6);
		CARD_MAP.put("71", R.drawable.hearts_7);
		CARD_MAP.put("81", R.drawable.hearts_8);
		CARD_MAP.put("91", R.drawable.hearts_9);
		CARD_MAP.put("101", R.drawable.hearts_10);
		CARD_MAP.put("111", R.drawable.hearts_11);
		CARD_MAP.put("121", R.drawable.hearts_12);
		CARD_MAP.put("131", R.drawable.hearts_13);
		CARD_MAP.put("141", R.drawable.hearts_1);
		CARD_MAP.put("24", R.drawable.spades_2);
		CARD_MAP.put("34", R.drawable.spades_3);
		CARD_MAP.put("44", R.drawable.spades_4);
		CARD_MAP.put("54", R.drawable.spades_5);
		CARD_MAP.put("64", R.drawable.spades_6);
		CARD_MAP.put("74", R.drawable.spades_7);
		CARD_MAP.put("84", R.drawable.spades_8);
		CARD_MAP.put("94", R.drawable.spades_9);
		CARD_MAP.put("104", R.drawable.spades_10);
		CARD_MAP.put("114", R.drawable.spades_11);
		CARD_MAP.put("124", R.drawable.spades_12);
		CARD_MAP.put("134", R.drawable.spades_13);
		CARD_MAP.put("144", R.drawable.spades_1);
		CARD_MAP.put("23", R.drawable.clubs_2);
		CARD_MAP.put("33", R.drawable.clubs_3);
		CARD_MAP.put("43", R.drawable.clubs_4);
		CARD_MAP.put("53", R.drawable.clubs_5);
		CARD_MAP.put("63", R.drawable.clubs_6);
		CARD_MAP.put("73", R.drawable.clubs_7);
		CARD_MAP.put("83", R.drawable.clubs_8);
		CARD_MAP.put("93", R.drawable.clubs_9);
		CARD_MAP.put("103", R.drawable.clubs_10);
		CARD_MAP.put("113", R.drawable.clubs_11);
		CARD_MAP.put("123", R.drawable.clubs_12);
		CARD_MAP.put("133", R.drawable.clubs_13);
		CARD_MAP.put("143", R.drawable.clubs_1);
		CARD_MAP.put("22", R.drawable.diamonds_2);
		CARD_MAP.put("32", R.drawable.diamonds_3);
		CARD_MAP.put("42", R.drawable.diamonds_4);
		CARD_MAP.put("52", R.drawable.diamonds_5);
		CARD_MAP.put("62", R.drawable.diamonds_6);
		CARD_MAP.put("72", R.drawable.diamonds_7);
		CARD_MAP.put("82", R.drawable.diamonds_8);
		CARD_MAP.put("92", R.drawable.diamonds_9);
		CARD_MAP.put("102", R.drawable.diamonds_10);
		CARD_MAP.put("112", R.drawable.diamonds_11);
		CARD_MAP.put("122", R.drawable.diamonds_12);
		CARD_MAP.put("132", R.drawable.diamonds_13);
		CARD_MAP.put("142", R.drawable.diamonds_1);
	}
	public static final Map<String, Integer> VERTICAL_OPPONENT_CARD_MAP = new HashMap<String, Integer>();
	static {
		VERTICAL_OPPONENT_CARD_MAP.put("21", R.drawable.op_hearts_2);
		VERTICAL_OPPONENT_CARD_MAP.put("31", R.drawable.op_hearts_3);
		VERTICAL_OPPONENT_CARD_MAP.put("41", R.drawable.op_hearts_4);
		VERTICAL_OPPONENT_CARD_MAP.put("51", R.drawable.op_hearts_5);
		VERTICAL_OPPONENT_CARD_MAP.put("61", R.drawable.op_hearts_6);
		VERTICAL_OPPONENT_CARD_MAP.put("71", R.drawable.op_hearts_7);
		VERTICAL_OPPONENT_CARD_MAP.put("81", R.drawable.op_hearts_8);
		VERTICAL_OPPONENT_CARD_MAP.put("91", R.drawable.op_hearts_9);
		VERTICAL_OPPONENT_CARD_MAP.put("101", R.drawable.op_hearts_10);
		VERTICAL_OPPONENT_CARD_MAP.put("111", R.drawable.op_hearts_11);
		VERTICAL_OPPONENT_CARD_MAP.put("121", R.drawable.op_hearts_12);
		VERTICAL_OPPONENT_CARD_MAP.put("131", R.drawable.op_hearts_13);
		VERTICAL_OPPONENT_CARD_MAP.put("141", R.drawable.op_hearts_1);
		VERTICAL_OPPONENT_CARD_MAP.put("24", R.drawable.op_spades_2);
		VERTICAL_OPPONENT_CARD_MAP.put("34", R.drawable.op_spades_3);
		VERTICAL_OPPONENT_CARD_MAP.put("44", R.drawable.op_spades_4);
		VERTICAL_OPPONENT_CARD_MAP.put("54", R.drawable.op_spades_5);
		VERTICAL_OPPONENT_CARD_MAP.put("64", R.drawable.op_spades_6);
		VERTICAL_OPPONENT_CARD_MAP.put("74", R.drawable.op_spades_7);
		VERTICAL_OPPONENT_CARD_MAP.put("84", R.drawable.op_spades_8);
		VERTICAL_OPPONENT_CARD_MAP.put("94", R.drawable.op_spades_9);
		VERTICAL_OPPONENT_CARD_MAP.put("104", R.drawable.op_spades_10);
		VERTICAL_OPPONENT_CARD_MAP.put("114", R.drawable.op_spades_11);
		VERTICAL_OPPONENT_CARD_MAP.put("124", R.drawable.op_spades_12);
		VERTICAL_OPPONENT_CARD_MAP.put("134", R.drawable.op_spades_13);
		VERTICAL_OPPONENT_CARD_MAP.put("144", R.drawable.op_spades_1);
		VERTICAL_OPPONENT_CARD_MAP.put("23", R.drawable.op_clubs_2);
		VERTICAL_OPPONENT_CARD_MAP.put("33", R.drawable.op_clubs_3);
		VERTICAL_OPPONENT_CARD_MAP.put("43", R.drawable.op_clubs_4);
		VERTICAL_OPPONENT_CARD_MAP.put("53", R.drawable.op_clubs_5);
		VERTICAL_OPPONENT_CARD_MAP.put("63", R.drawable.op_clubs_6);
		VERTICAL_OPPONENT_CARD_MAP.put("73", R.drawable.op_clubs_7);
		VERTICAL_OPPONENT_CARD_MAP.put("83", R.drawable.op_clubs_8);
		VERTICAL_OPPONENT_CARD_MAP.put("93", R.drawable.op_clubs_9);
		VERTICAL_OPPONENT_CARD_MAP.put("103", R.drawable.op_clubs_10);
		VERTICAL_OPPONENT_CARD_MAP.put("113", R.drawable.op_clubs_11);
		VERTICAL_OPPONENT_CARD_MAP.put("123", R.drawable.op_clubs_12);
		VERTICAL_OPPONENT_CARD_MAP.put("133", R.drawable.op_clubs_13);
		VERTICAL_OPPONENT_CARD_MAP.put("143", R.drawable.op_clubs_1);
		VERTICAL_OPPONENT_CARD_MAP.put("22", R.drawable.op_diamonds_2);
		VERTICAL_OPPONENT_CARD_MAP.put("32", R.drawable.op_diamonds_3);
		VERTICAL_OPPONENT_CARD_MAP.put("42", R.drawable.op_diamonds_4);
		VERTICAL_OPPONENT_CARD_MAP.put("52", R.drawable.op_diamonds_5);
		VERTICAL_OPPONENT_CARD_MAP.put("62", R.drawable.op_diamonds_6);
		VERTICAL_OPPONENT_CARD_MAP.put("72", R.drawable.op_diamonds_7);
		VERTICAL_OPPONENT_CARD_MAP.put("82", R.drawable.op_diamonds_8);
		VERTICAL_OPPONENT_CARD_MAP.put("92", R.drawable.op_diamonds_9);
		VERTICAL_OPPONENT_CARD_MAP.put("102", R.drawable.op_diamonds_10);
		VERTICAL_OPPONENT_CARD_MAP.put("112", R.drawable.op_diamonds_11);
		VERTICAL_OPPONENT_CARD_MAP.put("122", R.drawable.op_diamonds_12);
		VERTICAL_OPPONENT_CARD_MAP.put("132", R.drawable.op_diamonds_13);
		VERTICAL_OPPONENT_CARD_MAP.put("142", R.drawable.op_diamonds_1);
	}
	public static final Map<String, Integer> HORIZONTAL_OPPONENT_CARD_MAP = new HashMap<String, Integer>();
	static {
		HORIZONTAL_OPPONENT_CARD_MAP.put("21", R.drawable.hor_op_hearts_2);
		HORIZONTAL_OPPONENT_CARD_MAP.put("31", R.drawable.hor_op_hearts_3);
		HORIZONTAL_OPPONENT_CARD_MAP.put("41", R.drawable.hor_op_hearts_4);
		HORIZONTAL_OPPONENT_CARD_MAP.put("51", R.drawable.hor_op_hearts_5);
		HORIZONTAL_OPPONENT_CARD_MAP.put("61", R.drawable.hor_op_hearts_6);
		HORIZONTAL_OPPONENT_CARD_MAP.put("71", R.drawable.hor_op_hearts_7);
		HORIZONTAL_OPPONENT_CARD_MAP.put("81", R.drawable.hor_op_hearts_8);
		HORIZONTAL_OPPONENT_CARD_MAP.put("91", R.drawable.hor_op_hearts_9);
		HORIZONTAL_OPPONENT_CARD_MAP.put("101", R.drawable.hor_op_hearts_10);
		HORIZONTAL_OPPONENT_CARD_MAP.put("111", R.drawable.hor_op_hearts_11);
		HORIZONTAL_OPPONENT_CARD_MAP.put("121", R.drawable.hor_op_hearts_12);
		HORIZONTAL_OPPONENT_CARD_MAP.put("131", R.drawable.hor_op_hearts_13);
		HORIZONTAL_OPPONENT_CARD_MAP.put("141", R.drawable.hor_op_hearts_1);
		HORIZONTAL_OPPONENT_CARD_MAP.put("24", R.drawable.hor_op_spades_2);
		HORIZONTAL_OPPONENT_CARD_MAP.put("34", R.drawable.hor_op_spades_3);
		HORIZONTAL_OPPONENT_CARD_MAP.put("44", R.drawable.hor_op_spades_4);
		HORIZONTAL_OPPONENT_CARD_MAP.put("54", R.drawable.hor_op_spades_5);
		HORIZONTAL_OPPONENT_CARD_MAP.put("64", R.drawable.hor_op_spades_6);
		HORIZONTAL_OPPONENT_CARD_MAP.put("74", R.drawable.hor_op_spades_7);
		HORIZONTAL_OPPONENT_CARD_MAP.put("84", R.drawable.hor_op_spades_8);
		HORIZONTAL_OPPONENT_CARD_MAP.put("94", R.drawable.hor_op_spades_9);
		HORIZONTAL_OPPONENT_CARD_MAP.put("104", R.drawable.hor_op_spades_10);
		HORIZONTAL_OPPONENT_CARD_MAP.put("114", R.drawable.hor_op_spades_11);
		HORIZONTAL_OPPONENT_CARD_MAP.put("124", R.drawable.hor_op_spades_12);
		HORIZONTAL_OPPONENT_CARD_MAP.put("134", R.drawable.hor_op_spades_13);
		HORIZONTAL_OPPONENT_CARD_MAP.put("144", R.drawable.hor_op_spades_1);
		HORIZONTAL_OPPONENT_CARD_MAP.put("23", R.drawable.hor_op_clubs_2);
		HORIZONTAL_OPPONENT_CARD_MAP.put("33", R.drawable.hor_op_clubs_3);
		HORIZONTAL_OPPONENT_CARD_MAP.put("43", R.drawable.hor_op_clubs_4);
		HORIZONTAL_OPPONENT_CARD_MAP.put("53", R.drawable.hor_op_clubs_5);
		HORIZONTAL_OPPONENT_CARD_MAP.put("63", R.drawable.hor_op_clubs_6);
		HORIZONTAL_OPPONENT_CARD_MAP.put("73", R.drawable.hor_op_clubs_7);
		HORIZONTAL_OPPONENT_CARD_MAP.put("83", R.drawable.hor_op_clubs_8);
		HORIZONTAL_OPPONENT_CARD_MAP.put("93", R.drawable.hor_op_clubs_9);
		HORIZONTAL_OPPONENT_CARD_MAP.put("103", R.drawable.hor_op_clubs_10);
		HORIZONTAL_OPPONENT_CARD_MAP.put("113", R.drawable.hor_op_clubs_11);
		HORIZONTAL_OPPONENT_CARD_MAP.put("123", R.drawable.hor_op_clubs_12);
		HORIZONTAL_OPPONENT_CARD_MAP.put("133", R.drawable.hor_op_clubs_13);
		HORIZONTAL_OPPONENT_CARD_MAP.put("143", R.drawable.hor_op_clubs_1);
		HORIZONTAL_OPPONENT_CARD_MAP.put("22", R.drawable.hor_op_diamonds_2);
		HORIZONTAL_OPPONENT_CARD_MAP.put("32", R.drawable.hor_op_diamonds_3);
		HORIZONTAL_OPPONENT_CARD_MAP.put("42", R.drawable.hor_op_diamonds_4);
		HORIZONTAL_OPPONENT_CARD_MAP.put("52", R.drawable.hor_op_diamonds_5);
		HORIZONTAL_OPPONENT_CARD_MAP.put("62", R.drawable.hor_op_diamonds_6);
		HORIZONTAL_OPPONENT_CARD_MAP.put("72", R.drawable.hor_op_diamonds_7);
		HORIZONTAL_OPPONENT_CARD_MAP.put("82", R.drawable.hor_op_diamonds_8);
		HORIZONTAL_OPPONENT_CARD_MAP.put("92", R.drawable.hor_op_diamonds_9);
		HORIZONTAL_OPPONENT_CARD_MAP.put("102", R.drawable.hor_op_diamonds_10);
		HORIZONTAL_OPPONENT_CARD_MAP.put("112", R.drawable.hor_op_diamonds_11);
		HORIZONTAL_OPPONENT_CARD_MAP.put("122", R.drawable.hor_op_diamonds_12);
		HORIZONTAL_OPPONENT_CARD_MAP.put("132", R.drawable.hor_op_diamonds_13);
		HORIZONTAL_OPPONENT_CARD_MAP.put("142", R.drawable.hor_op_diamonds_1);
	}
}
